services:
  pg-primary:
    image: postgres:16
    container_name: pg-primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infinite_scaling
    volumes:
      - postgres-data-main:/var/lib/postgresql/data
      - ./docker/pg-primary/init-replication.sh:/docker-entrypoint-initdb.d/init-replication.sh:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pg-replica-1:
    image: postgres:16
    container_name: pg-replica-1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PRIMARY_HOST: pg-primary
      POSTGRES_PRIMARY_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infinite_scaling
      PGPASSWORD: replicator_pass
    volumes:
      - postgres-data-replica-1:/var/lib/postgresql/data
      - ./docker/pg-replica/entrypoint.sh:/entrypoint.sh:z
    entrypoint: ["bash", "/entrypoint.sh"]
    depends_on:
        pg-primary:
            condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pg-replica-2:
    image: postgres:16
    container_name: pg-replica-2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PRIMARY_HOST: pg-primary
      POSTGRES_PRIMARY_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infinite_scaling
      PGPASSWORD: replicator_pass
    volumes:
      - postgres-data-replica-2:/var/lib/postgresql/data
      - ./docker/pg-replica/entrypoint.sh:/entrypoint.sh:z
    entrypoint: ["bash", "/entrypoint.sh"]
    depends_on:
        pg-primary:
            condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data-main:
  postgres-data-replica-1:
  postgres-data-replica-2:
  redis-data:
